backend:
  name: test-repo

media_folder: static/assets
public_folder: assets

collections:
  - name: blog
    label: Blog
    folder: content/blog
    create: true
    fields:
      - { label: layout, name: layout, widget: hidden, default: "blog"}
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: tags, label: Tags , widget: list}
      - { name: body, label: Body, widget: markdown }

  - name: project
    label: Project
    folder: content/project
    create: true
    fields:
      - { label: layout, name: layout, widget: hidden, default: "project"}
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: name, label: Name }
      - { name: tags, label: Tags , widget: list}
      - { name: body, label: Body, widget: markdown }

  - name: review
    label: Review
    folder: content/review
    create: true
    fields:
      - { label: layout, name: layout, widget: hidden, default: "review"}
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: name, label: Name }
      - { name: type, label: Type }
      - { name: body, label: Body, widget: markdown }
