backend:
  name: test-repo

media_folder: static/assets
public_folder: assets

collections:
  - name: blog
    label: Blog
    folder: content/blog
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: body, label: Body, widget: markdown }

  - name: project
    label: Project
    folder: content/project
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: name, label: Name }
      - { name: tags, label: Tags }
      - { name: body, label: Body, widget: markdown }

  - name: book
    label: Book
    folder: content/book
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: name, label: Name }
      - { name: genre, label: Genre }
      - { name: body, label: Body, widget: markdown }
