backend:
  name: test-repo

media_folder: content/assets
public_folder: assets

collections:
  - name: blog
    label: Blog
    folder: content/blog
    create: true
    fields:
      - { label: layout, name: layout, widget: hidden, default: "blog" }
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: description, label: Description, required: false }
      - { name: tags, label: Tags, widget: list, required: false }
      - { label: Photo, name: photo, widget: image, required: false }
      - {
        name: externalUrl,
        label: Link,
        widget: string,
        pattern:
          [
            '^(http:\/\/|https:\/\/)[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(:[0-9]{1,5})?(\/.*)?$',
            "Must be a link(and start with http or https)!",
          ],
        required: false,
      }
      - { name: body, label: Body, widget: markdown, required: false}

  - name: project
    label: Project
    folder: content/project
    create: true
    fields:
      - { label: layout, name: layout, widget: hidden, default: "project" }
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: description, label: Description, required: false }
      - {
          name: externalUrl,
          label: Link,
          widget: string,
          pattern:
            [
              '^(http:\/\/|https:\/\/)[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(:[0-9]{1,5})?(\/.*)?$',
              "Must be a link(and start with http or https)!",
            ],
          required: false,
        }
      - { name: title, label: Title }
      - { name: tags, label: Tags, widget: list, required: false }
      - { label: Photo, name: photo, widget: image, required: false }
      - { name: body, label: Body, widget: markdown, required: false }

  - name: review
    label: Review
    folder: content/review
    create: true
    fields:
      - { label: layout, name: layout, widget: hidden, default: "review" }
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: description, label: Description, required: false }
      - { label: Photo, name: photo, widget: image, required: false }
      - { name: type, label: Type }
      - {
        name: externalUrl,
        label: Link,
        widget: string,
        pattern:
          [
            '^(http:\/\/|https:\/\/)[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(:[0-9]{1,5})?(\/.*)?$',
            "Must be a link(and start with http or https)!",
          ],
        required: false,
      }
      - { name: body, label: Body, widget: markdown, required: false }

  - label: Pages
    name: pages
    files:
      - label: About
        name: about
        file: /content/pages/about.yml
        fields:
          - { label: Name, name: name, widget: string }
          - { label: Nickname, name: nickname, widget: string, required: false }
          - { label: "About Me", name: aboutMe, widget: text }
          - { label: Quote, name: quote, widget: string }
          - { label: Photo, name: photo, widget: image }
          - label: Skills
            name: skills
            widget: list
            fields:
              - { label: Name, name: name, widget: string }
              - { label: Description, name: description, widget: text }
          - label: Links
            name: links
            widget: list
            fields:
              - { label: Name, name: name, widget: string }
              - {
                  label: "On Hover Color",
                  name: color,
                  widget: string,
                  pattern:
                    [
                      "^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$",
                      "Must be a hex color code!",
                    ],
                }
              - {
                  label: Link,
                  name: link,
                  widget: string,
                  pattern:
                    [
                      '^(http:\/\/|https:\/\/)[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(:[0-9]{1,5})?(\/.*)?$',
                      "Must be a link(and start with http or https)!",
                    ],
                }
              - { label: "Fab Icon Class", name: fabIconClass, widget: string }
